DEBUG = True

ALLOWED_IMAGE_EXTENSIONS = ["JPEG", "JPG", "PNG"]
MAX_IMAGE_FILESIZE = 100 * 1024 * 1024
IMAGE_UPLOADS = 'uploads'
API_KEY ='uPNlLvtXfhpnqQqEHuQx8jwwxvWUPW7ix0U9aIFGlcsiOdKYrd'
SECRET_KEY = b'dor9dor'
